<p align="center">
  <a href="https://imc.uc.cl" target="_blank">
    <img src="attachment:image.png" alt="IMC" width="220">
  </a>
</p>

# IMT 2200 - Introducción a Ciencia de Datos
**Pontificia Universidad Católica de Chile**<br>
**Instituto de Ingeniería Matemática y Computacional**<br>
**Profesor:** Rodrigo A. Carrasco <br>
---

## Tarea 04 – Aprendizaje automático

- **Fecha de Entrega:** 13 de noviembre de 2025, a las 23:59.
- **Fecha de publicación**: 30 de octubre de 2025.
- **Formato de entrega:** Notebook ejecutado y comentado (`.ipynb`) en el módulo de Tarea 04 habilitado en Canvas.

## Instrucciones

- Esta Tarea debe desarrollarse de manera totalmente *individual*, de acuerdo a lo establecido en la sección de Integridad Académica en el programa del curso.
- La Tarea debe ser desarrollada en lenguaje de programación Python y la entrega en formato Jupyter Notebook.
- El desarrollo del Notebook debe ser claro y ordenado, incluyendo anotaciones (markdown) y comentarios que permitan seguir fácilmente el código y los pasos implementados a los correctores, y siguiendo buenas prácticas de programación. La presentación y claridad del notebook y código forman parte de la evaluación de la tarea.
- Notebook **autocontenible** que:
   - Ejecute sin errores todas las celdas.
  - Contenga tanto el código como los comentarios y explicaciones necesarias.
  - Incluya visualizaciones claras y correctamente etiquetadas.
- No se aceptarán notebooks con celdas rotas o que dependan de rutas externas no indicadas en la tara.

- Deben hacer sus consultas y comentarios sobre la Tarea a traves del canal de Tareas en eo del curso en Canvas.os.
cteriza.

## 1. Objetivos

- Aplicar los conceptos iniciales de manejo de datos y análisis exploratorio vistos en clases.
- Practicar la lectura, limpieza y manipulación de datos en Python.
- Desarrollar habilidades para visualizar y describir patrones y tendencias en conjuntos de datos reales.
- Fomentar la capacidad de comunicar resultados de forma clara y fundamentada.

### 1.1 Objetivo educacional

Esta Tarea tiene como objetivo que los estudiantes desarrollen la capacidad de manejar algunas de las librerías centrales para el desarrollo de Ciencia de Datos, con foco en la lectura y exploración de datos. 

### 1.2 Pregunta de ciencia de datos

Esta tarea tendrá como objetivo crear un predictor que determine el éxito o fracaso de una expedición a distintas montañas del Himalayas según datos del montañista y de la expedición. Vamos a responder a la pregunta de qué tan bien pueden atributos como año, estación, montaña, edad del montañista, entre otros, predecir el éxito o fracaso de una expedición.

### 1.3 Recomendaciones
- Utiliza las librerías sugeridas en el notebook o justifica brevemente si incorporas otras.
- Revisa que todas las celdas se ejecuten en orden, desde el inicio, sin errores.
- Comenta tu código para explicar qué hace cada sección relevante.
- Asegúrate de que las visualizaciones sean fáciles de interpretar y tengan títulos y etiquetas adecuados.

## 2. Datos

[The Himalayan Database](https://www.himalayandatabase.com/) consiste en una colección de registros de expediciones en la cordillera del Himalaya. Esta contiene información detallada de las cimas más altas del mundo, junto con miles de expediciones realizadas desde 1905 hasta 2024 e información de cada uno de los/las montañistas que han participado en ellas. (El dataset que utilizaremos fue extraído desde: https://mavenanalytics.io/data-playground/himalayan-expeditions)

Descargue el archivo `Himalayan+Expeditions.zip` disponible en el repositorio del curso. Como puede ver, esta información está separada en varios archivos `.csv`. Deberá utilizar las herramientas aprendidas durante el curso para juntar esta información, procesarla y crear un predictor que determine el éxito de una subida.

**Recomendación**: Puede revisar el archivo `himalayan_data_dictionary.csv` para saber el significado de cada una de las columnas de la base de datos.

### 2.1 Librerías

Para esta tarea puede utilizar cualquiera de las librerías previamente utilizadas en el curso. Puede agregar otras si lo estima conveniente para el desarrollo de la Tarea.

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import zipfile
# ...agreuge otras librerías si lo considera relevante

## 3. Carga y limpieza (1 punto)

### 3.1 DataFrame unificado (0.2 pts)

Inspeccione los atributos de cada dataset y extraiga la siguiente información de ellos:

1. Información de las montañas:
    * ID de la cima (`peakid`)
    * Nombre común de la montaña (`pkname`)
    * Altura (m) (`heightm`)
    * Cantidad de expediciones exitosas (`success_exp`)
    * Cantidad de expediciones fallidas (`failed_exp`)

2. Información de las expediciones:
    * ID de la expedición (`expid`)
    * Año (`year`)
    * Estación del año (`season`)

3. Información de los montañistas:
    * ID del miembro (`memid`)
    * Sexo (`sex`)
    * Año de nacimiento (`yob`)
    * Nacionalidad (`citizen`)
    * Completó la expedición exitosamente (`msuccess`)

Genere un único DataFrame con todos estos atributos, donde cada fila represente el ascenso de un/a montañista en una expedición. (Ojo que esto no necesariamente significa que cada fila será una persona diferente: si una persona escaló dos cumbres distintas en dos expediciones, esta debería aparecer en su DataFrame como dos filas separadas.)

In [12]:
# respuestas
#['exped.csv', 'himalayan_data_dictionary.csv', 'members.csv', 'peaks.csv', 'refer.csv', 'peaks_with_exp.csv']

ruta_zip = "Himalayan+Expeditions.zip"

with zipfile.ZipFile(ruta_zip) as z:
    df1 = pd.read_csv(z.open("exped.csv"))
    df2 = pd.read_csv(z.open("himalayan_data_dictionary.csv"))
    df3 = pd.read_csv(z.open("members.csv"))
    df4 = pd.read_csv(z.open("peaks.csv"))
    df5 = pd.read_csv(z.open("refer.csv"), encoding="latin-1")  
    df6 = pd.read_csv(z.open("peaks_with_exp.csv"))

C:\Users\stgog\AppData\Local\Temp\ipykernel_13012\603470057.py:7: DtypeWarning: Columns (8,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv(z.open("exped.csv"))
C:\Users\stgog\AppData\Local\Temp\ipykernel_13012\603470057.py:9: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  df3 = pd.read_csv(z.open("members.csv"))

In [ ]:
df2

     Table       Field                                        Description
0    peaks         NaN                                                NaN
1    peaks      peakid                              Peak ID (primary key)
2    peaks      pkname                  Foreign (common) name of the peak
3    peaks     pkname2                             Local name of the peak
4    peaks    location                      Location of the climbing area
..     ...         ...                                                ...
160  refer  rpublisher                              Book publication date
161  refer    rpubdate  The language for a non-English publication or ...
162  refer   rlanguage                        Journal / magazine citation
163  refer   rcitation  The catalog number from the Catalogue of the H...
164  refer      ryak94                                    Reference notes

[165 rows x 3 columns]

In [21]:
df1[["expid","year","season"]]

           expid  year  season
0      ANN260101  1960  Spring
1      ANN269301  1969  Autumn
2      ANN273101  1973  Spring
3      ANN278301  1978  Autumn
4      ANN279301  1979  Autumn
...          ...   ...     ...
11420  PATR24201  2024  Summer
11421  PUMO24101  2024  Spring
11422  PUTH24101  2024  Spring
11423  TKPO24101  2024  Spring
11424  YLNG24101  2024  Spring

[11425 rows x 3 columns]

In [25]:
df3.columns

Index(['expid', 'membid', 'peakid', 'myear', 'mseason', 'fname', 'lname',
       'sex', 'yob', 'citizen', 'status', 'residence', 'occupation', 'leader',
       'deputy', 'bconly', 'nottobc', 'support', 'disabled', 'hired', 'sherpa',
       'tibetan', 'msuccess', 'mclaimed', 'mdisputed', 'msolo', 'mtraverse',
       'mski', 'mparapente', 'mspeed', 'mhighpt', 'mperhighpt', 'msmtdate1',
       'msmtdate2', 'msmtdate3', 'msmttime1', 'msmttime2', 'msmttime3',
       'mroute1', 'mroute2', 'mroute3', 'mascent1', 'mascent2', 'mascent3',
       'mo2used', 'mo2none', 'mo2climb', 'mo2descent', 'mo2sleep',
       'mo2medical', 'mo2note', 'death', 'deathdate', 'deathtime', 'deathtype',
       'deathhgtm', 'deathclass', 'msmtbid', 'msmtterm', 'hcn', 'mchksum'],
      dtype='object')

In [26]:
df3[["membid","sex","yob","citizen","msuccess"]]

       membid sex     yob    citizen  msuccess
0           2   M  1972.0  Australia     False
1           1   M  1968.0  Australia     False
2           3   M  1960.0  Australia     False
3           4   M  1966.0  Australia     False
4           5   F  1970.0  Australia     False
...       ...  ..     ...        ...       ...
88995       2   M  1944.0         UK     False
88996       3   M     NaN         UK     False
88997       4   M  1948.0         UK     False
88998       5   M     NaN         UK     False
88999       6   M  1948.0         UK     False

[89000 rows x 5 columns]

In [38]:
df3.columns

Index(['expid', 'membid', 'peakid', 'myear', 'mseason', 'fname', 'lname',
       'sex', 'yob', 'citizen', 'status', 'residence', 'occupation', 'leader',
       'deputy', 'bconly', 'nottobc', 'support', 'disabled', 'hired', 'sherpa',
       'tibetan', 'msuccess', 'mclaimed', 'mdisputed', 'msolo', 'mtraverse',
       'mski', 'mparapente', 'mspeed', 'mhighpt', 'mperhighpt', 'msmtdate1',
       'msmtdate2', 'msmtdate3', 'msmttime1', 'msmttime2', 'msmttime3',
       'mroute1', 'mroute2', 'mroute3', 'mascent1', 'mascent2', 'mascent3',
       'mo2used', 'mo2none', 'mo2climb', 'mo2descent', 'mo2sleep',
       'mo2medical', 'mo2note', 'death', 'deathdate', 'deathtime', 'deathtype',
       'deathhgtm', 'deathclass', 'msmtbid', 'msmtterm', 'hcn', 'mchksum'],
      dtype='object')

In [37]:
df1.columns

Index(['expid', 'peakid', 'year', 'season', 'host', 'route1', 'route2',
       'route3', 'route4', 'nation', 'leaders', 'sponsor', 'success1',
       'success2', 'success3', 'success4', 'ascent1', 'ascent2', 'ascent3',
       'ascent4', 'claimed', 'disputed', 'countries', 'approach', 'bcdate',
       'smtdate', 'smttime', 'smtdays', 'totdays', 'termdate', 'termreason',
       'termnote', 'highpoint', 'traverse', 'ski', 'parapente', 'camps',
       'rope', 'totmembers', 'smtmembers', 'mdeaths', 'tothired', 'smthired',
       'hdeaths', 'nohired', 'o2used', 'o2none', 'o2climb', 'o2descent',
       'o2sleep', 'o2medical', 'o2taken', 'o2unkwn', 'othersmts', 'campsites',
       'accidents', 'achievment', 'agency', 'comrte', 'stdrte', 'primrte',
       'primmem', 'primref', 'primid', 'chksum'],
      dtype='object')

In [29]:
df6.columns

Index(['peakid', 'pkname', 'pkname2', 'location', 'heightm', 'heightf',
       'himal', 'region', 'open', 'unlisted', 'trekking', 'trekyear',
       'restrict', 'phost', 'pstatus', 'pyear', 'pseason', 'pmonth', 'pday',
       'pexpid', 'pcountry', 'psummiters', 'psmtnote', 'failed_exp',
       'success_exp'],
      dtype='object')

In [36]:
df4.columns

Index(['peakid', 'pkname', 'pkname2', 'location', 'heightm', 'heightf',
       'himal', 'region', 'open', 'unlisted', 'trekking', 'trekyear',
       'restrict', 'phost', 'pstatus', 'pyear', 'pseason', 'pmonth', 'pday',
       'pexpid', 'pcountry', 'psummiters', 'psmtnote'],
      dtype='object')

In [30]:
df6[["peakid","pkname","heightm","success_exp","failed_exp"]]

    peakid               pkname  heightm  success_exp  failed_exp
0     ACHN               Aichyn     6055            2           1
1     AMAD           Ama Dablam     6814         1123         453
2     AMOT             Amotsang     6393            1           2
3     AMPG        Amphu Gyabjen     5630            3           1
4     AMPH              Amphu I     6740            1           1
..     ...                  ...      ...          ...         ...
475   YAUP                Yaupa     6422            1           2
476   YLNG          Yalung Peak     7590            0           1
477   YNGS  Yangra Kangri South     6863            0           0
478   YOKO            Yokopahar     6423            0           0
479   YUBR                Yubra     6264            0           0

[480 rows x 5 columns]

In [ ]:
# los junte agregando las flas peakid y expid para el df de miembros ya que asi los podia conectar de buena manera 
em = pd.merge(df3[["membid","sex","yob","citizen","msuccess","expid","peakid"]], df1[["expid","year","season"]], on="expid", how="inner")
df_final = pd.merge(em, df6[["peakid","pkname","heightm","success_exp","failed_exp"]], on="peakid", how="inner")
df_final

,membid,sex,yob,citizen,msuccess,expid,peakid,year,season,pkname,heightm,success_exp,failed_exp
0,2,M,1972.0,Australia,False,AMAD01101,AMAD,2001,Spring,Ama Dablam,6814,1123,453
1,1,M,1968.0,Australia,False,AMAD01101,AMAD,2001,Spring,Ama Dablam,6814,1123,453
2,3,M,1960.0,Australia,False,AMAD01101,AMAD,2001,Spring,Ama Dablam,6814,1123,453
3,4,M,1966.0,Australia,False,AMAD01101,AMAD,2001,Spring,Ama Dablam,6814,1123,453
4,5,F,1970.0,Australia,False,AMAD01101,AMAD,2001,Spring,Ama Dablam,6814,1123,453
...,...,...,...,...,...,...,...,...,...,...,...,...,...
89084,2,M,1944.0,UK,False,SURM74101,SURM,1974,Spring,Surma-Sarovar North,6564,1,3
89085,3,M,NaN,UK,False,SURM74101,SURM,1974,Spring,Surma-Sarovar North,6564,1,3
89086,4,M,1948.0,UK,False,SURM74101,SURM,1974,Spring,Surma-Sarovar North,6564,1,3
89087,5,M,NaN,UK,False,SURM74101,SURM,1974,Spring,Surma-Sarovar North,6564,1,3
89088,6,M,1948.0,UK,False,SURM74101,SURM,1974,Spring,Surma-Sarovar North,6564,1,3

### 3.2 Limpieza y transformación (0.2 pts)

Inspeccione y procese su DataFrame para generar uno nuevo llamado `clean_df`. En esta sección usted debe decidir si es necesario:

* Limpiar valores nulos, duplicados o inválidos.
* Imputar valores.
* Transformar tipos de columnas.

Justifique su procesamiento.

In [ ]:
# respuestas

### 3.2 Creación de nuevas columnas (0.6 pts)

Vamos a crear un par de columnas nuevas que nos ayudarán a hacer una análisis exploratorio del dataset.
Utilizando las columnas actuales, genere y agregue las siguientes columnas a su DataFrame:

* `age`: Edad del montañista a la fecha de la expedición.
* `peak_success_p`: Porcentaje de expediciones exitosas de la cima respectiva.

De ser necesario, aplique procesos de limpieza y transformación a estas columnas también (asegúrese de que todos los valores sean coherentes).

In [ ]:
# respuestas

## 4. EDA (2.5 puntos)

Con el dataset obtenido, responda las siguientes preguntas. Para cada una de ellas, realice al menos un gráfico que permita visualizar el comportamiento de su dataset.

a. **(0.5 pts)** ¿Cuántos ascensos exitosos y fallidos hay en su dataset? ¿A qué porcentaje del total corresponde cada categoría?

b. **(0.5 pts)** ¿Cómo se distribuyen las edades de los/las montañistas en la base de datos?

c. **(0.5 pts)** ¿Cómo se distribuye la cantidad de ascensos según estación del año? ¿Cuál es el porcentaje de éxito por estación? Muestre la cantidad de filas de ascensos exitosas y fallidas para cada estación.

d. **(0.5 pts)** ¿Cómo cambia la cantidad de ascensos en el tiempo? Muestre la cantidad de ascensos exitosos y fallidos por año.

e. **(0.5 pts)** ¿Existe una correlación entre el porcentaje de éxito de ascenso y la altura de una cumbre? Haga un scatterplot para todas las cumbres que hayan sido escaladas por al menos 10 expediciones en total (tanto fallidas como exitosas).

In [ ]:
# respuestas

Respuestas:

## 5. Predictor (2.5 puntos)

Ahora veremos si la información que tenemos nos permite predecir el éxito de un ascenso por alguna persona en particular. Primero, defina su **X** (matriz de atributos) e **y** (etiqueta a predecir) de la siguiente manera:

* **X**: `age`, `sex`, `citizen`, `season`, `heightm`, `year`, `success_exp`, `failed_exp`
* **y**: `msuccess`

Luego, realice los pasos a continuación:

**5.1 Codificación y normalización (1 pto)**
* Codifique todas las columnas categóricas, de manera que su matriz **X** solo tenga valores numéricos.
* Divida sus datos en sets de entrenamiento y testeo. Use una división de 70-30.
* Normalice sus matrices de atributos. Justifique su método de normalización.

**5.2 Creación y entrenamiento de modelos (1 pto)**
* Cree y entrene los siguientes modelos:
    * Un clasificador KNN
    * Un árbol de decisión
    * Un clasificador de regresión logística
    * Un clasificador random forest **(Opcional)**

    Explique qué hiperparámetros utilizó para la creación de cada uno de ellos y qué valores le asignó.

* Finalmente, evalúe todos sus modelos con el set de testeo. Para cada uno, muestre
    * Accuracy
    * Precisión
    * Recall
    * Matriz de confusión

**5.3 Análisis de resultados (0.5 pts)**

Interprete, analice y comente sus resultados. 
* ¿Qué tendencias puede observar? ¿Se diferencian de alguna forma las predicciones entre un modelo y otro? 
* ¿Fue posible construir un predictor efectivo? Justique.

In [ ]:
# respuestas

Respuestas: